name: udisks2
adopt-info: udisks2
summary: Storage devices management service
description: |
    Udisks2 provides a dbus service that can query and manager
    storages devices as well as a command-line tool.
confinement: strict
base: core24

lint:
  ignore:
    - library:
      - usr/lib/**/libbd_*.so*
      # Used by libbd_mdraid
      - usr/lib/**/libbytesize.so*
      - usr/lib/**/libmpfr.so*
      # Used by libbd_nvme
      - usr/lib/**/libnvme*.so*
      # Used by libbd_crypto
      - usr/lib/**/libvolume_key.so*

slots:
  udisks2-dbus:
    interface: dbus
    bus: system
    name: org.freedesktop.UDisks2

  udisks2:
    udev-file: usr/lib/udev/rules.d/80-udisks2.rules

plugs:
  udisks2-client:
    interface: udisks2

  polkit:
    action-prefix: org.freedesktop.udisks2

apps:
  udisksd:
    command: usr/libexec/udisks2/udisksd
    daemon: dbus
    plugs:
      - hardware-observe
      - mount-observe
      - polkit
    slots:
      - udisks2
    daemon-scope: system
    activates-on:
      - udisks2-dbus

  udisksctl:
    command: usr/bin/udisksctl
    plugs:
      - udisks2-client

layout:
  /usr/var/lib/udisks2:
    bind: $SNAP/usr/var/lib/udisks2
  /usr/etc/udisks2:
    bind: $SNAP/usr/etc/udisks2
  /etc/libblockdev/conf.d:
    bind: $SNAP/etc/libblockdev/conf.d

parts:
  udisks2-copyright:
    plugin: nil
    stage-packages:
      - udisks2
    override-build: |
      cp -r "${CRAFT_PART_INSTALL}/usr/share/doc" doc
      rm -rf "${CRAFT_PART_INSTALL}"
      install -Dm644 -t "${CRAFT_PART_INSTALL}/usr/share/doc/udisks2" doc/udisks2/copyright doc/udisks2/changelog.*

  udisks2:
    build-environment:
      - XDG_DATA_DIRS: "/usr/local/share/:/usr/share/:${CRAFT_STAGE}/usr/share/"
    build-packages:
      - meson
      - pkg-config
      - libglib2.0-dev
      - libgudev-1.0-dev
      - libblockdev-dev
      - libatasmart-dev
      - libblockdev-part-dev
      - libblockdev-loop-dev
      - libblockdev-swap-dev
      - libblockdev-mdraid-dev
      - libblockdev-fs-dev
      - libblockdev-nvme-dev
      - libblockdev-crypto-dev
      - libpolkit-agent-1-dev
      - libpolkit-gobject-1-dev
      - gettext
      - xsltproc
      - docbook-xsl
      - polkitd
    stage-packages:
      - libatasmart4
      - libblockdev-crypto3
      - libblockdev-fs3
      - libblockdev-loop3
      - libblockdev-loop3
      - libblockdev-mdraid3
      - libblockdev-nvme3
      - libblockdev-part3
      - libblockdev-swap3
      - libblockdev-swap3
      - libblockdev-utils3
      - libblockdev3
      - libgudev-1.0-0
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-fhs-media
    source-type: git
    source-branch: applied/ubuntu/noble
    source: https://git.launchpad.net/ubuntu/+source/udisks2
    override-pull: |
      craftctl default
      patch -p1 <"${CRAFT_PROJECT_DIR}/proc-mountinfo.patch"
      git_ver="$(git describe --tags --match "applied/*")"
      git_ver="${git_ver#importer/}"
      git_ver="${git_ver#applied/}"
      git_ver="${git_ver%-0-g*}"
      craftctl set version="${git_ver}"

  policy:
    plugin: nil
    after:
      - udisks2
    override-build: |
      install -Dm644 \
        "${CRAFT_STAGE}/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy" \
        "${CRAFT_PART_INSTALL}/meta/polkit/polkit.org.freedesktop.UDisks2.policy"
